PROJECT/PETSHOP/PETSHOP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]
if(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

PROJECT/PETSHOP/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
     path('addtocart/<p>',views.add_to_cart,name='addtocart'),
     path('cartview',views.cartview,name='cartview'),
     path('cart_remove/<p>',views.cart_remove,name='cart_remove'),
     path('full_remove/<p>',views.full_remove,name='full_remove'),
     path('orderform',views.orderform,name='orderform'),
     path('orderview',views.orderview,name='orderview'),
]

PROJECT/PETSHOP/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name='search'
urlpatterns = [
path('search',views.search,name='search'),
]

PROJECT/PETSHOP/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'

urlpatterns = [
    path('',views.allcategories,name='allcat'),
    path('allproducts/<p>',views.allproducts,name="allproducts"),
    path('detail/<p>',views.detail,name='detail'),
    path('reg',views.register,name='register'),
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout'),

]

PROJECT/PETSHOP/cart/models.py
from django.db import models
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price


class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.CharField(max_length=30)
    order_status=models.CharField(max_length=20,default='pending')
    delivery_status=models.CharField(max_length=20,default='pending')
    date_ordered=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username

class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

PROJECT/PETSHOP/search/models.py
from django.db import models

# Create your models here.

PROJECT/PETSHOP/shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    image=models.ImageField(upload_to='shop/categories',blank=True,null=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    image=models.ImageField(upload_to='shop/products',blank=True,null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

PROJECT/PETSHOP/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart
from cart.models import Account,Order


def cartview(request):
    total=0

    u=request.user

    try:
     cart=Cart.objects.filter(user=u)
     for i in cart:
         total+=i.quantity*i.product.price
    except:
        pass
    return render(request,'cart.html',{'c':cart,'total':total})


@login_required
def add_to_cart(request,p):
    product=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=product)
        if(cart.quantity<cart.product.stock):
            cart.quantity+=1
        cart.save()

    except:
        cart=Cart.objects.create(product=product,user=u,quantity=1)
        cart.save()
    return redirect('cart:cartview')

def cart_remove(request,p):
    p=Product.objects.get(name=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=p)
        if cart.quantity>1:
            cart.quantity-=1

            cart.save()
        else:
            cart.delete()

    except:
        pass
    return redirect('cart:cartview')

def full_remove(request,p):
    p=Product.objects.get(name=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=p)
        cart.delete()

    except:
        pass
    return redirect('cart:cartview')

def orderform(request):
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        u=request.user
        cart=Cart.objects.filter(user=u)

        total=0
        for i in cart:
            total+=i.quantity*i.product.price

        ac=Account.objects.get(acctnum=n)
        if(ac.amount>=total):
            ac.amount=ac.amount-total
            ac.save()

            for i in cart:
                o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status='paid')
                o.save()
                i.product.stock=i.product.stock-i.quantity
                i.product.save()
            cart.delete()
            msg="Order Placed Successfully"
            return render(request,'orderdetail.html',{'m':msg})


        else:
            msg="Insufficient Amount in User Account.You Cannot Place Order."
            return render(request,'orderform.html',{'m':msg})


    return render(request,'orderform.html')

def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'u':u.username,'o':o})

PROJECT/PETSHOP/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

# Create your views here.
def search(request):
    q=""
    product=None
    if(request.method=='POST'):
        q=request.POST['q']
        if q:
            product=Product.objects.filter(Q(name__icontains=q))
    return render(request,'search.html',{'p':product,'query':q})

PROJECT/PETSHOP/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from shop.models import Category,Product
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=Product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})


def detail(request,p):
    product=Product.objects.get(name=p)
    return render(request,'detail.html',{'p':product})

def register(request):
    if(request.method=='POST'):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        e=request.POST['e']


        if(p==cp):
           u=User.objects.create_user(username=u,password=p,email=e)
           u.save()
           return redirect('shop:allcat')
        else:
          return HttpResponse('Password Not Matching')


    return render(request,'register.html')



def user_login(request):
     if(request.method=='POST'):
        name=request.POST['u']
        pass1=request.POST['p']
        user=authenticate(username=name,password=pass1)



        if user:
            login(request,user)
            return redirect('shop:allcat')
        else:
              messages.error(request,"Invalid Credentials")

     return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

PROJECT/PETSHOP/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/xon.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Madimi+One&display=swap" rel="stylesheet">
</head>
<body>
<header>
    <center>
        <img src="{% static 'images/logo2.jpg' %}" class="mb-2" height="80px" width="160px"
    </center>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <div class="container-fluid">
    <b><a class="navbar-brand" href="#">petZworld</a></b>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{i.name}}</a></li>{% endfor %}


          </ul>
        {% if user.is_authenticated %}
          {% if user.is_superuser == False %}


          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i>&nbsp;&nbsp;<sub>{{count}}</sub></a>
        </li>

          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">Your Order</a>
        </li>
          {% endif %}


          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
        {% else %}

          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
                  <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>

        {% endif %}

      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="What are you looking for" aria-label="Search">

        <button class="btn btn-outline-dark btn-#ff6347" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}
{% endblock %}
<footer>

    <div class="footer bg-warning text-center">
        <p class="text-dark"><i class="fa-regular fa-copyright text-dark"></i>petZworld pvt ltd.All Rights Reserved.</p>
    </div>
</footer>

</body>
</html>

PROJECT/PETSHOP/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not c %}
<div class="container-mt-3">
    <h3 class="text-center">Cart is empty</h3>
    <h3 class="text-center text-success"><a href="{% url 'shop:allcat' %}">Continue shopping</a></h3>

</div>
{% else %}
<div class="container-fluid m-3">
<div class="row">
    <h4 class="text-center">SHOPPING CART</h4>


    <div class="col-sm-6">
     <table class="table table-bordered">
         <tr><th colspan="5" class="text-center bg-warning">CART ITEMS</th></tr>
        {% for i in c %}
        <tr>
            <td><img src="{{i.product.image.url}}" height="150px" width="150px"></td>
            <td><b>{{i.product.name}}</b></td>
            <td><b>Product id:{{i.product.id}}</b><br>
                <b>Unit Price:{{i.product.price}}</b><br>
                <b>Quantity:{{i.quantity}}*{{i.product.price}}</b></td>
            <td><b>Subtotal:{{i.subtotal}}</b></td>
            <td>
                {% if i.quantity < i.product.stock %}
                <a href="{% url 'cart:addtocart' i.product.name %}"><i style="color:black;" class="fa-solid fa-circle-plus"></i></a>
                <a href="{% url 'cart:cart_remove' i.product.name %}""><i style="color:black"; class="fa-solid fa-circle-minus"></i></a>
                <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black"; class="fa-solid fa-trash"></i></a></td>

                {% else %}
                <a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black"; class="fa-solid fa-circle-minus"></i></a>
                <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black"; class="fa-solid fa-trash"></i></a></td>
        </tr>
                {% endif %}
        {% endfor %}
     </table>
    </div>
    <div class="col-sm-5">
        <table class="table table-bordered">
            <tr><th colspan="4" class="text-center bg-warning">CHECK OUT</th></tr>
            <tr><td class="text-center"><b>TOTAL:<span class="text-dark">{{total}}</span><b/></td></tr>
        </table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-dark " style="position:absolute;left:52%;"><b>Place Order</b></a>
        <a href="{% url 'shop:allcat' %}" class="btn btn-dark " style="position:absolute;right:8%;"> <b>Continue Shopping</b></a>
    </div>

{% endif %}

{% endblock %}

PROJECT/PETSHOP/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
  <img src="{% static 'images/pet3.jpg' %}" height="700px" width="100%">
</div>
<div class="container-fluid mt-4 " style="margin-bottom:50px;">
    <h3 class="text-center">100% Safe Arrival Guarantee</h3>
    <p style="'text-align:justify;">Trust and convenience of ethical, healthy, and sustainable pets, pet accessories, and pet-care solutions. petZworld is the fruit of labour and love. Brought to you by a collective of experienced pet-lovers, citizen scientists, and hobbyists. We believe - Pets are simply the best.</p>
</div>
            <a href="http://127.0.0.1:8000/allproducts/Pet%20Food">
 <img src="{% static 'images/whiskas.jpg' %}" height="400px" width="100%">
</a>

    <h3 class="text-center">PRODUCTS</h3>

</div>


<div class="container-fluid mt-3"style="margin-bottom:100px;">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4">

            <div class="card" style="width:32rem;margin-bottom:50px;">
                            <a href="{% url 'shop:allproducts' i.name %}">
 <img src="{{i.image.url}}" class="card-img-top" alt="..." height="300px" width="100%">
</a>

  <div class="card-body bg-warning">
    <h3 class="card-title text-center">{{i.name}}</h3>
      <a href="{% url 'shop:allproducts' i.name %}" class="btn btn-dark" style="position:relative;left:38%;">Shop Now</a>



  </div>
</div>
        </div>{% endfor %}
        <div class="container-fluid mt-4 " style="margin-bottom:50px;">
            <a href="http://127.0.0.1:8000/detail/Vet%20Consultation">
 <img src="{% static 'images/vetconsult1.jpg' %}" height="400px" width="100%">
</a>


    <h3 class="text-center">Our Story</h3>
    <p style="'text-align:justify;">petZworld began with humble beginnings and a single store. It grew slowly and organically through the years, now we have 6 stores across Mumbai and a pan India presence with our website. Our aim has always been to provide the largest range of pet products at reasonable prices and make the shopping experience comfortable for pet parents.

We are a family run business that has built its online presence through the foundation of the brick and mortar stores. We hope to continue to serve the pet parent community with passion, drive and commitment. Read more to find out a bit more about our family!

</p>
</div>

        <div class="container-fluid mt-0  " style="margin-bottom:30px;">
            <h3 class="text-center">Address:</h3>
    <p style="text-align:center"> 1335, 11th Cross Rd, Stage 3,<br> Indiranagar, Bengaluru, Karnataka 560038<br>
        contact:+91-987654321<br>
        email:petZworld@gmail.com

    </p>
</div>

    </div>
</div>

{% endblock %}

PROJECT/PETSHOP/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mt-4" style="margine-bottom:100px;margin-left:25px">
<div class="row">
  <div class="col-sm-4"><img src="{{p.image.url}}"height="400px" width="470px"></div>
   <div class="col-sm-5">
     <h4>{{p.name}}</h4>
     <h5>{{p.price}}</h5>
     <p style="text-indent:20px;line-height:2;text-align:justify">{{p.desc}}</p>
       {% if user.is_superuser == False %}

       {% if p.stock <= 0 %}
       <h4>Out of Stock</h4>
       {% else %}

       <h4><a href="{% url 'cart:addtocart' p.name %}" class="btn btn-dark" style="position:absolute;left:50%;">Add To Cart </a></h4>

       {% endif %}
       {% else %}

       {% if p.stock <= 0 %}
       <h4>Out of Stock</h4>

       <h4><a href="{% url 'admin:index' %}" class="btn btn-dark mt-4">Add Stock</a></h4>
       {% else %}
       <h4>Product in Stock</h4>
       <h4><a href="{% url 'admin:index' %}" class="btn btn-dark mt-4">Add Stock</a></h4>

     {% endif %}
     {% endif %}


   </div>
 </div>

{% endblock %}

PROJECT/PETSHOP/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>LOGIN PAGE</h2>
<form method="POST">
    {% csrf_token %}

        <div class="mb-3">
            <label class="form-label">Username</label>
            <input type="text" class="form-control"name="u" placeholder="Enter the user name">
        </div>

        <div class="mb-3">
            <label class="form-label">Password</label>
            <input type="password" class="form-control"name="p" placeholder="Enter the password">
        </div>

        <div class="mb-3">
        <input type="submit" class="form-control">
        </div>

</form>

{% if messages %}
{% for i in messages %}
<ul>
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}


{% endblock %}

PROJECT/PETSHOP/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid m-5">
    <center>
        <h3 class="text-center text-dark">{{m}}</h3>
        <img src="{% static 'images/thankyou1.jpg' %}" height="300px" width="500px"><br>
        <a href="{% url 'shop:allcat' %}" class="btn btn-dark " style="position:absolute;right:42%;"> <b>Continue Shopping</b></a>


    </center>
</div>


  {% endblock %}

PROJECT/PETSHOP/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Enter Details</h2>
<form method="POST">
    {% csrf_token %}

        <div class="mb-3">
            <label class="form-label">Address</label>
            <input type="text" class="form-control"name="a" placeholder="Enter the Address">
        </div>

        <div class="mb-3">
            <label class="form-label">Phone</label>
            <input type="text" class="form-control"name="p" placeholder="Enter the Phone Number">
        </div>

        <div class="mb-3">
            <label class="form-label">Account Number</label>
            <input type="text" class="form-control"name="n" placeholder="Enter the Account Number">
        </div>

        <center>
        <div class="mb-3">
        <input type="submit" class="btn btn-dark " >
        </div>
            </center>

</form>


{% endblock %}

PROJECT/PETSHOP/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mt-5">
<h4>Customer Name:{{u}}</h4>
    <div class="row">
        <h4>Order Details:</h4>
        {% for i in o %}
        <div class="col-sm-4   border border-1 border-dark bg-warning">
            <center><img src="{{i.product.image.url}}" height="180px" width="250px"></center>

        </div>


        <div class="col-sm-8 my-0 text-center border border-1 border-dark bg-warning">
            <b>Delivery Address:{{i.address}}</b><br>
            <b>Customer Phone Number:{{i.phone}}</b><br>
            <b>Product Name:{{i.product.name}}</b><br>
            <b>Price:{{i.product.price}}</b><br>
            <b>No of Items:{{i.no_of_items}}</b><br>
            <b>Ordered on:{{i.date_ordered}}</b><br>
            <b>Delivery Status:<span class="text-dark">{{i.delivery_status}}</span></b><br>
        </div>
    {% endfor %}
    </div>

</div>


{% endblock %}

PROJECT/PETSHOP/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-4" style="margine-bottom:100px;">
<img src="{{c.image.url}}" width="100%" height="600px"></div>

<div class="container-fluid mt-4" style="margin-bottom:30px;">
    <h3 class="text-center">{{c.name}}</h3>
    <p style="'text-align:justify;">{{c.desc}}</p>
</div>


<div class="container-fluid mt-3"style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width:32rem;margin-bottom:50px;">
                                            <a href="{% url 'shop:detail' i.name %}">
 <img src="{{i.image.url}}" class="card-img-top " alt="..." height="300px" width="100%">
</a>

  <div class="card-body bg-warning">
    <h3 class="card-title text-center">{{i.name}}</h3>
      <h5 class="text-center">{{i.price}}</h5>


    <a href="{% url 'shop:detail' i.name %}" class="btn btn-dark" style="position:relative;left:41%;">Details</a>

  </div>
</div>
        </div>{% endfor %}
    </div>
</div>

{% endblock %}

PROJECT/PETSHOP/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <h2>REGISTER HERE</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username</label>
            <input type="text" class="form-control"name="u" placeholder="Enter the username">
        </div>
        <div class="mb-3">
            <label class="form-label">Password</label>
            <input type="password" class="form-control"name="p" placeholder="Enter the password">
        </div>
        <div class="mb-3">
            <label class="form-label">Confirm Password</label>
            <input type="password" class="form-control"name="cp" placeholder="Enter the confirm password">
        </div>
                <div class="mb-3">
            <label class="form-label">email</label>
            <input type="email" class="form-control"name="e" placeholder="Enter the email">
        </div>
    <div class="mb-3">
        <input type="submit" class="form-control">
    </div>
    </form>

</div>

{% endblock %}

PROJECT/PETSHOP/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>



<div class="container-fluid mt-3"style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width: 30rem;">
                <img src="{{i.image.url}}" class="card-img-top" alt="..." height="250px;width:100%;">
  <div class="card-body bg-warning">
    <h3 class="card-title text-center">{{i.name}}</h3>
      <h5 class="text-center">{{i.price}}</h5>


    <a href="{% url 'shop:detail' i.name %}" class="btn btn-dark" style="position:relative;left:0%;">Details</a>

  </div>
</div>
        </div>
{% empty %}
        <h4 class="text-center text-dark">No search result found</h4>
        {% endfor %}
    </div>
</div>
{% endblock %}